package com.ecobin;

import android.app.Application;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import java.util.Arrays;
import java.util.List;

public class PackageList {
  private Application application;
  private ReactNativeHost reactNativeHost;

  public PackageList(ReactNativeHost reactNativeHost) {
    this(reactNativeHost, null);
  }

  public PackageList(Application application) {
    this(null, application);
  }

  public PackageList(ReactNativeHost reactNativeHost, Application application) {
    this.reactNativeHost = reactNativeHost;
    this.application = application;
  }

  private ReactNativeHost getReactNativeHost() {
    return this.reactNativeHost;
  }

  private Application getApplication() {
    return this.application;
  }

  public List<ReactPackage> getPackages() {
    // Packages are auto-generated by autolinking
    @SuppressWarnings("UnnecessaryLocalVariable")
    List<ReactPackage> packages = Arrays.<ReactPackage>asList(
      new com.reactnativecommunity.asyncstorage.AsyncStoragePackage(),
      new com.swmansion.gesturehandler.RNGestureHandlerPackage(),
      new com.swmansion.reanimated.ReanimatedPackage(),
      new com.th3rdwave.safeareacontext.SafeAreaContextPackage(),
      new com.swmansion.rnscreens.RNScreensPackage()
    );
    return packages;
  }
}
